// client/src/routes/auth/+page.svelte
<script lang="ts">
	import { Tabs } from 'bits-ui';
	import { cn } from '$lib/utils';
	import { AuthClient } from '$lib/transport';
	import { goto } from '$app/navigation';
	import { ConnectError } from '@connectrpc/connect';
	import { toast } from 'svelte-sonner';
	import Button from '$lib/ui/Button.svelte';
	import Input from '$lib/ui/Input.svelte';

	let tab = $state('login');
</script>

<div class="flex h-screen flex-col items-center justify-center">
	<Tabs.Root bind:value={tab} class="w-[390px] p-3">
		<Tabs.List
			class="bg-mantle border-surface-0 flex w-full justify-around gap-1 rounded-lg border p-1 drop-shadow-md"
		>
			<Tabs.Trigger
				value="login"
				class={cn(
					'hover:bg-surface-0 grow cursor-pointer rounded p-2 transition-all',
					tab == 'login' && 'bg-surface-0'
				)}>Log In</Tabs.Trigger
			>
			<Tabs.Trigger
				value="signup"
				class={cn(
					'hover:bg-surface-0 grow cursor-pointer rounded p-2 transition-all',
					tab == 'signup' && 'bg-surface-0'
				)}>Sign Up</Tabs.Trigger
			>
		</Tabs.List>
		<Tabs.Content
			value="login"
			class="bg-mantle border-surface-0 mt-2 rounded-lg border p-6 drop-shadow-md"
		>
			<form
				onsubmit={async (e) => {
					e.preventDefault();
					const formData = new FormData(e.target as HTMLFormElement);
					const username = formData.get('login-username')?.toString();
					const password = formData.get('login-password')?.toString();

					try {
						const response = await AuthClient.login({
							username: username,
							password: password
						});

						if (response.token && username) {
							goto('/');
						}
					} catch (err) {
						const error = ConnectError.from(err);
						toast.error(error.rawMessage);
					}
				}}
			>
				<div class="flex flex-col gap-4">
					<div class="flex flex-col gap-1">
						<label for="login-username" class="text-sm">Username</label>
						<Input name="login-username" />
					</div>
					<div class="flex flex-col gap-1">
						<label for="login-password" class="text-sm">Password</label>
						<Input name="login-password" type="password" />
					</div>
					<Button type="submit">Submit</Button>
				</div>
			</form>
		</Tabs.Content>
		<Tabs.Content
			value="signup"
			class="bg-mantle border-surface-0 mt-2 rounded-lg border p-6 drop-shadow-md"
		>
			<form
				onsubmit={async (e) => {
					e.preventDefault();
					const form = e.target as HTMLFormElement;
					const formData = new FormData(form);

					try {
						await AuthClient.signUp({
							username: formData.get('signup-username')?.toString(),
							password: formData.get('signup-password')?.toString(),
							confirmPassword: formData.get('signup-confirm-password')?.toString()
						});

						toast.success('account created successfully, please log in');
						form.reset();
						tab = 'login';
					} catch (err) {
						const error = ConnectError.from(err);
						toast.error(error.rawMessage);
					}
				}}
			>
				<div class="flex flex-col gap-4">
					<div class="flex flex-col gap-1">
						<label for="signup-username" class="text-sm">Username</label>
						<Input name="signup-username" />
					</div>
					<div class="flex flex-col gap-1">
						<label for="signup-password" class="text-sm">Password</label>
						<Input name="signup-password" />
					</div>
					<div class="flex flex-col gap-1">
						<label for="signup-confirm-password" class="text-sm">Confirm Password</label>
						<Input name="signup-confirm-password" />
					</div>
					<Button type="submit">Submit</Button>
				</div>
			</form>
		</Tabs.Content>
	</Tabs.Root>
</div>

// web/routes/auth/auth.tsx
import { LoginRequestSchema } from "$connect/auth/v1/login_pb";
import { SignupRequestSchema } from "$connect/auth/v1/signup_pb";
import { getReturnPath, session } from "$lib/auth";
import { Card } from "$lib/card";
import { AuthClient } from "$lib/connect";
import { Form } from "$lib/form/form";
import { type MessageFormController, useForm } from "$lib/form/hook";
import { SubmitButton } from "$lib/form/submit-button";
import { TextField } from "$lib/form/text-field";
import { Tabs } from "$lib/tabs";
import { toaster } from "$lib/toast";
import { useNavigate } from "@solidjs/router";
import { Effect } from "effect";
import type { Component } from "solid-js";

export const Auth: Component = () => {
  const navigate = useNavigate();
  const returnTo = getReturnPath(window.location.search, window.location.origin);

  const loginForm = useForm(LoginRequestSchema, () => ({
    validation: {
      onMount: true,
      onChange: true,
    },
    onSubmit: ({ value }) =>
      AuthClient.login({ username: value.username, password: value.password }).pipe(
        Effect.tap(rememberSession),
        Effect.match({
          onSuccess: () => {
            toaster.success({ title: "Signed in" });
            navigate(returnTo, { replace: true });
          },
          onFailure: (err) => {
            toaster.error({
              title: "Failed to sign in",
              description: err.message,
            });
          },
        }),
        Effect.runPromise,
      ),
  }));

  const signupForm = useForm(SignupRequestSchema, () => ({
    validation: {
      onMount: true,
      onChange: true,
    },
    onSubmit: ({ value }) =>
      Effect.gen(function* () {
        yield* AuthClient.signup({ username: value.username, password: value.password });
        return yield* AuthClient.login({ username: value.username, password: value.password });
      }).pipe(
        Effect.tap(rememberSession),
        Effect.match({
          onSuccess: () => {
            toaster.success({ title: "Account created" });
            navigate(returnTo, { replace: true });
          },
          onFailure: (err) => {
            toaster.error({
              title: "Failed to create account",
              description: err.message,
            });
          },
        }),
        Effect.runPromise,
      ),
  }));

  return (
    <div class="flex h-body flex-col items-center justify-center gap-4 px-4">
      <h1 class="text-2xl font-bold">Welcome to TrevStack</h1>
      <Card class="w-full max-w-sm">
        <Tabs.Root defaultValue="login">
          <Tabs.List aria-label="Authentication" class="grid w-full grid-cols-2">
            <Tabs.Trigger value="login">Login</Tabs.Trigger>
            <Tabs.Trigger value="signup">Sign up</Tabs.Trigger>
          </Tabs.List>
          <Tabs.Content value="login">
            <LoginForm form={loginForm} />
          </Tabs.Content>
          <Tabs.Content value="signup">
            <SignupForm form={signupForm} />
          </Tabs.Content>
        </Tabs.Root>
      </Card>
    </div>
  );
};

const LoginForm: Component<{
  form: MessageFormController<typeof LoginRequestSchema>;
}> = (props) => (
  <Form form={props.form} class="flex-col">
    <TextField field={props.form.field("username")} label="Username" autocomplete="username" />
    <TextField
      field={props.form.field("password")}
      label="Password"
      type="password"
      autocomplete="current-password"
    />
    <SubmitButton form={props.form} label="Login" />
  </Form>
);

const SignupForm: Component<{
  form: MessageFormController<typeof SignupRequestSchema>;
}> = (props) => (
  <Form form={props.form} class="flex-col">
    <TextField field={props.form.field("username")} label="Username" autocomplete="username" />
    <TextField
      field={props.form.field("password")}
      label="Password"
      type="password"
      autocomplete="new-password"
    />
    <SubmitButton form={props.form} label="Create account" />
  </Form>
);

function rememberSession(response: { sub: string; exp: bigint }) {
  return Effect.try({
    try: () => session.setFromLogin({ sub: response.sub, exp: response.exp }),
    catch: () => new Error("Could not read your session. Please sign in again."),
  });
}
